### ISSUE TITLE
Error in rebuild

### ISSUE THREAD

**Issue by DareenAlluhaybi** [hzli-ucas/warp-ctc_vs2015_pytorch1.0#4]
Goof evening 
When I did "rebuild" to "ALL BUILD" file, I got this error "Error LNK1104 cannot open file 'Debug\warpctc.lib",  and I searched for solutions but it's not worked.

What can I do?

Thank you.

**Comment by hzli-ucas** [comment]
I guess, you got stuck at the following step?
Open the `warp-ctc/build/ctc_release.sln` with vs2017, and build the project `ALL_BUILD` (**Release x64**).
If so, the error may be caused by the build configuration, Try change it to **Release x64** before the building.

Please feel free to contact me if there are any problems.

**Comment by DareenAlluhaybi** [comment]
Thank you so much, it's work.

Sorry but I got a new error after doing this step.
When I did this step: python setup.py install
I got this error: LINK : fatal error LNK1181: cannot open input file 'warpctc.lib'

Do you know what should I do?

Thank you.

**Comment by hzli-ucas** [comment]
Check the files under the path `warp-ctc/build/Release`, to ensure the `warpctc.lib` has been generated after you build the project. If not, try to rebuild the project.
According to my experience, after the successfully build the project, there should be four files under the path, including `test_cpu.exe`, `warpctc.dll`, `warpctc.exp` and `warpctc.lib`.
